using System.Drawing.Imaging;

namespace HooksNotifier;

/// <summary>
/// Loads the bell icon from icon.ico (ships with the app).
/// Highlighted variant is generated by tinting the normal icon orange.
/// </summary>
internal static class IconHelper
{
    private static Icon? _normal;
    private static Icon? _highlighted;
    private static Icon? _blank;
    private static string? _iconPath;

    public static Icon Normal => _normal ??= LoadIcon(false);
    public static Icon Highlighted => _highlighted ??= LoadIcon(true);
    public static Icon Blank => _blank ??= CreateBlankIcon();

    /// <summary>Set path to icon.ico (called once at startup).</summary>
    public static void SetPath(string dir)
    {
        _iconPath = dir != null ? Path.Combine(dir, "icon.ico") : null;
    }

    private static Icon LoadIcon(bool highlighted)
    {
        if (_iconPath != null && File.Exists(_iconPath))
        {
            var icon = new Icon(_iconPath, 32, 32);
            if (highlighted)
                icon = TintIcon(icon, Color.FromArgb(0xE8, 0x59, 0x0C));
            return icon;
        }

        // Fallback: draw a simple colored circle
        return CreateFallback(highlighted);
    }

    /// <summary>Tint an icon by overlaying a color on its grayscale version.</summary>
    private static Icon TintIcon(Icon source, Color tint)
    {
        using var bmp = source.ToBitmap();
        int w = bmp.Width, h = bmp.Height;
        using var result = new Bitmap(w, h, PixelFormat.Format32bppArgb);

        for (int y = 0; y < h; y++)
        {
            for (int x = 0; x < w; x++)
            {
                var px = bmp.GetPixel(x, y);
                if (px.A == 0) continue;
                // Preserve brightness from original, tint with the given color
                float brightness = (px.R * 0.299f + px.G * 0.587f + px.B * 0.114f) / 255f;
                var tinted = Color.FromArgb(
                    px.A,
                    (byte)(tint.R * brightness),
                    (byte)(tint.G * brightness),
                    (byte)(tint.B * brightness));
                result.SetPixel(x, y, tinted);
            }
        }
        return Icon.FromHandle(result.GetHicon());
    }

    private static Icon CreateFallback(bool highlighted)
    {
        var color = highlighted
            ? Color.FromArgb(0xE8, 0x59, 0x0C)
            : Color.FromArgb(0x12, 0x96, 0xDB);
        using var bmp = new Bitmap(32, 32, PixelFormat.Format32bppArgb);
        using var g = Graphics.FromImage(bmp);
        g.Clear(Color.Transparent);
        using var brush = new SolidBrush(color);
        g.FillEllipse(brush, 4, 4, 24, 24);
        return Icon.FromHandle(bmp.GetHicon());
    }

    public static void Cleanup()
    {
        if (_normal != null) { DestroyIcon(_normal.Handle); _normal = null; }
        if (_highlighted != null) { DestroyIcon(_highlighted.Handle); _highlighted = null; }
        if (_blank != null) { DestroyIcon(_blank.Handle); _blank = null; }
    }

    /// <summary>Create a fully transparent icon matching Normal's dimensions.</summary>
    private static Icon CreateBlankIcon()
    {
        int w = Normal.Width, h = Normal.Height;
        using var bmp = new Bitmap(w, h, PixelFormat.Format32bppArgb);
        return Icon.FromHandle(bmp.GetHicon());
    }

    [System.Runtime.InteropServices.DllImport("user32.dll")]
    private static extern bool DestroyIcon(IntPtr hIcon);
}
